GesagtGetan:
  KrakenOptimizer:
    liveOptimization: false
    requestOptions:
      base_uri: 'https://api.kraken.io/v1/upload'
    krakenOptions:
      auth:
        api_key: null
        api_secret: null
      lossy: true
Neos:
  Flow:
    mvc:
      routes:
        GesagtGetan.KrakenOptimizer:
          position: start
