GesagtGetan:
  KrakenOptimizer:
    liveOptimization: false
    # Optimize original resource if no thumbnail generation occured
    # This is the case if the image size is equal or smaller than the requested thumbnail
    optimizeOriginalResource: false
    requestOptions:
      base_uri: 'https://api.kraken.io/v1/upload'
    krakenOptions:
      auth:
        api_key: null
        api_secret: null
      lossy: true
Neos:
  Flow:
    mvc:
      routes:
        GesagtGetan.KrakenOptimizer:
          position: start
    persistence:
      doctrine:
        eventListeners:
          GesagtGetan\KrakenOptimizer\EventListener\ThumbnailEventListener:
            events:
              - postUpdate
            listener: GesagtGetan\KrakenOptimizer\EventListener\ThumbnailEventListener
